version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: miscellaneous/Codedeploy/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: miscellaneous/Codedeploy/AfterInstall.sh
      timeout: 300
      runas: root
